apiVersion: v1
kind: Pod
metadata:
  name: flask-app-pod  # Name of your pod
  labels:
    app: flask-app  # Custom label for this pod
spec:
  containers:
    - name: flask-app-container
      image: nanditad48/image_processor:0.0.1  # Replace with your actual Docker image
      ports:
        - containerPort: 5000  # The port your Flask app listens on
      env:
        - name: FLASK_ENV
          value: "production"  # Example environment variable
  restartPolicy: Always