apiVersion: v1
kind: Service
metadata:
  name: image-processing-np-service
spec:
  type: NodePort
  selector:
    app: flask-app  # This must match the labels on your Flask app's pod
  ports:
    - port: 5000        # The port exposed by the service
      targetPort: 5000  # The port on the pod (Flask app is listening on port 5000)
      nodePort: 30000   # The port exposed on each node (can be any port in the range 30000-32767)