apiVersion: v1
kind: ServiceAccount
metadata:
  name: prom-api-user
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cluster-admin-prom-api-user
subjects:
- kind: ServiceAccount
  name: prom-api-user
  namespace: default
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: Secret
metadata:
  name: prom-api-user-secret
  annotations:
    kubernetes.io/service-account.name: prom-api-user
type: kubernetes.io/service-account-token
# TOKEN=$(kubectl get secret prom-api-user-secret -o jsonpath='{.data.token}' | base64 --decode)