---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-server
spec:
  capacity:
    storage: 8Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  nfs:
    server: 172.31.1.230
    path: "/mnt/data/k8s-storage/prometheus-server"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: storage-prometheus-alertmanager-0
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  nfs:
    server: 172.31.1.230
    path: "/mnt/data/k8s-storage/prometheus-alertmanager"