apiVersion: apps/v1
kind: Deployment
metadata:
  name: vod-app-deployment-ap-south-1  # Unique name for ap-south-1
  labels:
    app: vod-app
    region: ap-south-1  # Label to identify this deployment's region
spec:
  replicas: 0  # Number of pod replicas to run in this region
  selector:
    matchLabels:
      app: vod-app
      region: ap-south-1
  template:
    metadata:
      labels:
        app: vod-app
        region: ap-south-1  # Ensure pods are labeled with the region
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: topology.kubernetes.io/region  # Ensure pods run only on nodes in this region
                    operator: In
                    values:
                      - ap-south-1
      containers:
      - name: vod-app-container
        image: nanditad48/vod:latest
        ports:
        - containerPort: 5000
        env:
          - name: FLASK_ENV
            value: "production"
        resources:
          requests:
            cpu: "150m"
          limits:
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: vod-np-service-ap-south-1  # Unique NodePort service for ap-south-1
spec:
  type: NodePort
  selector:
    app: vod-app
    region: ap-south-1  # Ensure the service only routes to pods in ap-south-1
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30001  # Port exposed on nodes
