apiVersion: apps/v1
kind: Deployment
metadata:
  name: vod-app-deployment-us-west-1  # Unique name for us-west-1
  labels:
    app: vod-app
    region: us-west-1
spec:
  replicas: 1  # Number of pod replicas to run in this region
  selector:
    matchLabels:
      app: vod-app
      region: us-west-1
  template:
    metadata:
      labels:
        app: vod-app
        region: us-west-1
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: topology.kubernetes.io/region
                    operator: In
                    values:
                      - us-west-1
      containers:
      - name: vod-app-container
        image: nanditad48/vod:latest
        ports:
        - containerPort: 5000
        env:
          - name: FLASK_ENV
            value: "production"
        resources:
          requests:
            cpu: "450m"
          limits:
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: vod-np-service-us-west-1  # Unique NodePort service for us-west-1
spec:
  type: NodePort
  selector:
    app: vod-app
    region: us-west-1
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30002  # Port exposed on nodes
